Fianarana/src/Entity/Versement.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VersementRepository")
 */
class Versement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $numVersement;

    /**
     * @ORM\Column(type="integer")
     */
    private $numCheque;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_compte;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumVersement(): ?int
    {
        return $this->numVersement;
    }

    public function setNumVersement(int $numVersement): self
    {
        $this->numVersement = $numVersement;

        return $this;
    }

    public function getNumCheque(): ?int
    {
        return $this->numCheque;
    }

    public function setNumCheque(int $numCheque): self
    {
        $this->numCheque = $numCheque;

        return $this;
    }

    public function getNumCompte(): ?int
    {
        return $this->num_compte;
    }

    public function setNumCompte(int $num_compte): self
    {
        $this->num_compte = $num_compte;

        return $this;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): self
    {
        $this->montant = $montant;

        return $this;
    }
}

Fianarana/src/Form/VersementType.php
<?php

namespace App\Form;

use App\Entity\Versement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VersementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numVersement')
            ->add('numCheque')
            ->add('num_compte')
            ->add('montant')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Versement::class,
        ]);
    }
}

Fianarana/src/Controller/VersementController.php
<?php

namespace App\Controller;

use App\Entity\Versement;
use App\Form\VersementType;
use App\Repository\VersementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/versement")
 */
class VersementController extends AbstractController
{
    /**
     * @Route("/", name="versement_index", methods={"GET"})
     */
    public function index(VersementRepository $versementRepository): Response
    {
        return $this->render('versement/index.html.twig', [
            'versements' => $versementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="versement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $versement = new Versement();
        $form = $this->createForm(VersementType::class, $versement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($versement);
            $entityManager->flush();

            return $this->redirectToRoute('versement_index');
        }

        return $this->render('versement/new.html.twig', [
            'versement' => $versement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="versement_show", methods={"GET"})
     */
    public function show(Versement $versement): Response
    {
        return $this->render('versement/show.html.twig', [
            'versement' => $versement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="versement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Versement $versement): Response
    {
        $form = $this->createForm(VersementType::class, $versement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('versement_index', [
                'id' => $versement->getId(),
            ]);
        }

        return $this->render('versement/edit.html.twig', [
            'versement' => $versement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="versement_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Versement $versement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$versement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($versement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('versement_index');
    }
}

Fianarana/templates/versement/_delete_form.html.twig
<form method="post" action="{{ path('versement_delete', {'id': versement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ versement.id) }}">
    <button class="btn">Delete</button>
</form>

Fianarana/templates/versement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Fianarana/templates/versement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Versement{% endblock %}

{% block body %}
    <h1>Edit Versement</h1>

    {{ include('versement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('versement_index') }}">back to list</a>

    {{ include('versement/_delete_form.html.twig') }}
{% endblock %}

Fianarana/templates/versement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Versement index{% endblock %}

{% block body %}
    <h1>Versement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>NumVersement</th>
                <th>NumCheque</th>
                <th>Num_compte</th>
                <th>Montant</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for versement in versements %}
            <tr>
                <td>{{ versement.id }}</td>
                <td>{{ versement.numVersement }}</td>
                <td>{{ versement.numCheque }}</td>
                <td>{{ versement.numCompte }}</td>
                <td>{{ versement.montant }}</td>
                <td>
                    <a href="{{ path('versement_show', {'id': versement.id}) }}">show</a>
                    <a href="{{ path('versement_edit', {'id': versement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('versement_new') }}">Create new</a>
{% endblock %}

Fianarana/templates/versement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Versement{% endblock %}

{% block body %}
    <h1>Create new Versement</h1>

    {{ include('versement/_form.html.twig') }}

    <a href="{{ path('versement_index') }}">back to list</a>
{% endblock %}

Fianarana/templates/versement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Versement{% endblock %}

{% block body %}
    <h1>Versement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ versement.id }}</td>
            </tr>
            <tr>
                <th>NumVersement</th>
                <td>{{ versement.numVersement }}</td>
            </tr>
            <tr>
                <th>NumCheque</th>
                <td>{{ versement.numCheque }}</td>
            </tr>
            <tr>
                <th>Num_compte</th>
                <td>{{ versement.numCompte }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ versement.montant }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('versement_index') }}">back to list</a>

    <a href="{{ path('versement_edit', {'id': versement.id}) }}">edit</a>

    {{ include('versement/_delete_form.html.twig') }}
{% endblock %}